### ISSUE TITLE
Add new section "Next.js"

### ISSUE THREAD

**Issue by v1rtl** [palashmon/awesome-js-posts#16]
[Next.js](nextjs.org/) is one of the most popular full-stack frameworks at the moment. I think it's worth creating a separate section for that.

Some articles for that list:
- [Building a Realtime GraphQL Chat Application With SMS Notifications](https://levelup.gitconnected.com/building-a-realtime-graphql-chat-application-with-sms-notifications-cc8ecbd0ada0)
- [Why I Got Rid of getInitialProps in My Next.js Project](https://betterprogramming.pub/why-i-got-rid-of-getinitialprops-in-my-next-js-project-fc926e98ed61)
- [Real-time Page Views with Next.js and Supabase](https://codebycorey.com/blog/page-views-nextjs-supabase)
- [Authentication Patterns for Next.js](https://leerob.io/blog/nextjs-authentication)

**Comment by palashmon** [comment]
Awesome, thanks! I will look into this soon.
