### ISSUE TITLE
First link under git returns 404

### ISSUE THREAD

**Issue by dahse89** [palashmon/awesome-js-posts#19]
I just want to let you know the link https://dev.to/devdefinitive/25-git-commands-i-use-daily-and-you-should-know-1kj5 is not available anymore.

**Comment by palashmon** [comment]
Thank you for letting me know about this. 👍🏻 

This issue is fixed now in this commit https://github.com/palashmon/awesome-js-posts/commit/d724cb0b5cd6f51b9032fbe367536006be4997d4
